image:
  name: cirrusci/flutter

stages:
- coverage
- release
- deploy



.prepare_android: &prepare_android |-
  cd android
  echo $FDROID_KEY | base64 --decode --ignore-garbage > key.jks
  echo "storePassword=${FDROID_KEY_PASS}" >> key.properties
  echo "keyPassword=${FDROID_KEY_PASS}" >> key.properties
  echo "keyAlias=key" >> key.properties
  echo "storeFile=../key.jks" >> key.properties
  cd ..


code_analyze:
  stage: coverage
  script:
    - flutter pub get
    - flutter format lib/ test/ --set-exit-if-changed
    - flutter analyze

build_apk_debug:
  stage: coverage
  before_script:
    - flutter pub get
  script:
    - flutter build apk
  artifacts:
    when: on_success
    paths:
      - build/app/outputs/apk/debug/app-release.apk
  except:
    - main
    - tags

build_apk:
  stage: coverage
  before_script:
    - *prepare_android
    - flutter pub get
  script:
    - flutter build apk --release
  artifacts:
    when: on_success
    paths:
      - build/app/outputs/apk/release/app-release.apk
  only:
    - main
    - tags

build_appbundle:
  stage: coverage
  before_script:
    - *prepare_android
    - flutter pub get
  script:
    - flutter build appbundle --target-platform android-arm,android-arm64
  artifacts:
    when: on_success
    paths:
      - build/app/outputs/bundle/release/app-release.aab
  only:
    - main
    - tags

