name: fun_with_kanji
description: Simple Flutter app to learn Japanese writing systems Hiragana, Katakana and Kanji.
publish_to: "none"
version: 0.3.2+5

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  yaru: ^0.3.2
  yaru_icons: ^0.2.1
  just_audio: ^0.9.20
  url_launcher: ^6.0.20
  file_picker_cross: ^4.6.0
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  isar_generator: ^2.2.1
  build_runner: any
  flutter_launcher_icons: "^0.9.2"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/sounds/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
