name: fun-with-kanji
version: git
summary: Fun With Kanji
description: |
    With Fun With Kanji you are able to learn **all** common used Japanese characters. All starts with Hiragana, Katakana and their special cases and combinations. After this you learn the Kanji Radicals and then you are ready to start with the 2136 Jōyō-Kanji. You no longer need 4 different apps to learn them!

    The app also contains a dictionary and a full-text search over all characters.

    Fun With Kanji is open source under Mozilla Public License 2.0. Contributions and new translations are always welcome <3.

    Website: https://gitlab.com/KrilleFear/funny-kanji

confinement: strict
base: core18

parts:
  fun-with-kanji:
    plugin: flutter
    source: ./
    flutter-target: lib/main.dart

apps:
  fun-with-kanji:
    command: fun_with_kanji
    extensions: [flutter-stable]